### PR TITLE
Update default Android version to 24

### PR DESCRIPTION
**Pull request by kchodorow**
Stopgap (but not the proper fix) for https://github.com/bazelbuild/continuous-integration/issues/74.

### CODE REVIEW

**Comment by aj-michael** [comment]
I think we can just delete this line. android_sdk_repository will use the highest available API level if none is installed. Same for build_tools_version. I think we should just remove the lines that set api_level and build_tools_version.

**Comment by aj-michael** [comment]
Augh, I think that https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/android/android_integration_test.sh#L389 will only pass with API level 24.

**Comment by kchodorow** [comment]
This isn't used for android_integration_test.sh (different repo!). Removed the lines.

**Comment by aj-michael** [comment]
Ah, you're right! LGTM.

**Pull request merged**
