### PR TITLE
Update examples to use the Starlark version of the Android rules.

### LINKED ISSUE #454: [Bazel CI] Error name 'aar_import' is not defined with Bazel@HEAD
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3858#018f7a6e-38e7-484f-9452-93b2e739d7a2

 Platform: Ubuntu, MacOs, Windows

 Logs: 
```
ERROR: [0m/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/f761224a263130470633a48378e6e87d/external/maven/BUILD:43:1: name 'aar_import' is not defined (did you mean 'cc_import'?)
``` 
 Culprit: https://github.com/bazelbuild/bazel/commit/947c72d699321c97518dbebe0e8ca59621b5da21

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/examples
git reset 4679b3915ebdec89b319c4da376b339484c7bf81  --hard
export USE_BAZEL_VERSION=88a230f4cf28deec1455cb2caed4dc9f81e108c9
bazel build  //app:app 
 ``` 
 CC Greenteam @fweikert

### PR DESCRIPTION
**Pull request by ahumesky**
Also disable a windows test until rules_android adds windows support

Fixes #454.

### CODE REVIEW

**Review by ted-xie — APPROVED** [review]

**Comment by alexeagle** [comment]
Hooray, it's green! This will unblock other PRs.

@fweikert could you approve/merge pls?

**Comment by sgowroji** [comment]
Hi Team, Any update on this PR ? As it is awaiting to merge?

**Comment by alexeagle** [comment]
Alternatively @meteorcloudy if we don't prioritize keeping `main` green, could I have the ability to merge changes here on red? It's blocking us on the rules_js 2.0 release.

**Review by meteorcloudy — APPROVED** [review]

**Comment by meteorcloudy** [comment]
Merged, and I removed the code owner approval requirement to speed things up, they'll still be notified.

**Pull request merged**
