### PR TITLE
chore: delete stale tutorial content

### PR DESCRIPTION
**Pull request by alexeagle**
1. This contains an iOS app, but the main iOS tutorial linked from https://bazel.build/start/ios-app lives elsewhere
2. It shows rules_appengine, but that repo appears to have only minimal maintenance for broken flags. Latest comment from a maintainer is 'not being actively maintained' https://github.com/bazelbuild/rules_appengine/issues/128#issuecomment-1194862052
3. bazelbuild/codelabs was archived, but there are active community forks at https://github.com/engflow/codelabs and https://github.com/aspect-build/codelabs which have fresher content than this tutorials folder.
4. No one has touched tutorial/android in four years.

### CODE REVIEW

**Comment by BalestraPatrick** [comment]
From rules_apple's side, we're okay with removing this since we already have a version of this tutorial which we maintain in rules_apple: https://github.com/bazelbuild/rules_apple/blob/master/doc/tutorials/ios-app.md

**Comment by gregestren** [comment]
Re: Android, note https://bazel.build/start/android-app refers to this repo. Particularly `examples/android/tutorial`.

https://github.com/bazelbuild/examples/tree/main/android/tutorial is different than https://github.com/bazelbuild/examples/tree/main/tutorial/android ?

This looks reasonable to me but paging @ahumesky .

**Comment by alexeagle** [comment]
Correct, `/android/tutorial` should remain, `/tutorial/android` looks like dead code.

**Comment by alexeagle** [comment]
ping @gregestren could you ask Alex to look? I don't think he has setup notifications from GitHub or doesn't notice them.

**Comment by alexeagle** [comment]
ping @meisterT

**Comment by ahumesky** [comment]
Looks fine to remove redundant tutorials/samples/examples

**Pull request merged**
