### PR TITLE
Fix the contents of BUILD for java-tutorial

### PR DESCRIPTION
**Pull request by seckin206**
The contents of the BUILD file was from a later stage in tutorial.

### CODE REVIEW

**Comment by seckin206** [comment]
I signed it!

**Comment by laurentlb** [comment]
Looks like the tests are failing

**Comment by seckin206** [comment]
@laurentlb the failed tests are coming from (seemingly) unrelated tests. I am not sure how to proceed at this point. Any suggestions? Is master branch building successfully at all?

**Comment by seckin206** [comment]
Tests are now green, please have another look @iirina

**Pull request merged**
