### PR TITLE
Add presubmit configuration.

### PR DESCRIPTION
**Pull request by fweikert**
Add initial presubmit configuration to be used by https://buildkite.com/bazel/bazel-bazel-examples

It's expected that we need to modify the configuration once we get the first test result from Buildkite.

Fixes https://github.com/bazelbuild/continuous-integration/issues/225.

### CODE REVIEW

**Comment by fweikert** [comment]
Actually buchgr@ set up a webhook so that this PR should have triggered a run on Buildkite :(

**Comment by fweikert** [comment]
Nvm, I forgot to check a checkbox on Buildkite.

**Comment by fweikert** [comment]
Current plan: Merge this PR, then find team members that can fix the example projects.

**Comment by laurentlb** [comment]
> Current plan: Merge this PR, then find team members that can fix the example projects.

Sounds good.

**Pull request merged**
