### PR TITLE
chore: setup renovate

### PR DESCRIPTION
**Pull request by alexeagle**
This should automatically send PRs to upgrade our dependencies, keeping the repo fresh as new rules versions are released.

### CODE REVIEW

**Comment by alexeagle** [comment]
Ping @gregestren

**Comment by alexeagle** [comment]
ping @meteorcloudy @meisterT

**Review by gregestren — COMMENTED** [review]
The idea looks cool but I don't know the tool.

Looking at https://github.com/renovatebot/tutorial

- does it require more setup than just adding a .json file?
- How does it identify these types of dependencies?

**Comment by meisterT** [comment]
Greg, see https://docs.renovatebot.com/bazel/

**Review by meisterT — APPROVED** [review]

**Pull request merged**
